xcopy ..\bin\release\PthreadVC2.dll .\bin\release\ /y
xcopy ..\bin\release\SamKernel.dll .\bin\release\ /y
xcopy ..\bin\release\SamGeom.dll .\bin\release\ /y
xcopy ..\bin\release\SamCore*.dll .\bin\release\ /y
xcopy ..\bin\release\AnySamGeom.dll .\bin\release\ /y
xcopy ..\bin\release\AnyCore*.dll .\bin\release\ /y
xcopy ..\bin\release\AnyData*.dll .\bin\release\ /y
xcopy ..\bin\release\AnyViz*.dll .\bin\release\ /y
xcopy ..\bin\release\AnyExchange*.dll .\bin\release\ /y
xcopy ..\bin\release\AnyPlatformAPI.dll .\bin\release\ /y
xcopy ..\bin\release\AnyCAD.*.dll .\bin\release\ /y
xcopy ..\bin\release\AppProConfig.xml .\bin\release\ /y